### ISSUE TITLE
FlySystem v3 support

### ISSUE THREAD

**Issue by stempora** [emgag/flysystem-tempdir#1]
Hello, 

Considering V2 is compatible with V3, can you modify composer.json to allow installation under v3 too ?

Thanks.

**Comment by maetthu** [comment]
Hi. Sorry about my late response. In the meantime, there has been a PR adding support for v3, so this should be released shortly. I'll close this issue here, see #2 for updates.

**Comment by maetthu** [comment]
Released as v3.0.0 https://packagist.org/packages/emgag/flysystem-tempdir#v3.0.0

**Comment by stempora** [comment]
Thank you!
